# Generated by Django 6.0.4 on 2026-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_team',
            field=models.CharField(default='Operations Team', max_length=100),
        ),
    ]
