# Generated by Django 6.0.4 on 2026-04-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessage',
            name='sms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
